---
sudo: false
language: ruby
bundler_args: --without system_tests
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
matrix:
  fast_finish: true
  include:
  # PE 2015.2.0
  - rvm: 2.1.6
    env:
      - PUPPET_GEM_VERSION="4.2.1"
      - FACTER_GEM_VERSION="3.0.2"
      - HIERA_GEM_VERSION="3.0.1"
  # PE 2015.2.2 and PE 2015.2.1
  - rvm: 2.1.6
    env:
      - PUPPET_GEM_VERSION="4.2.2"
      - FACTER_GEM_VERSION="3.1.0"
      - HIERA_GEM_VERSION="3.0.3"
  # PE 2015.2.3
  - rvm: 2.1.7
    env:
      - PUPPET_GEM_VERSION="4.2.3"
      - FACTER_GEM_VERSION="3.1.1"
      - HIERA_GEM_VERSION="3.0.4"
  # PE 2015.3.0 and PE 2015.3.1
  - rvm: 2.1.7
    env:
      - PUPPET_GEM_VERSION="4.3.1"
      - FACTER_GEM_VERSION="3.1.3"
      - HIERA_GEM_VERSION="3.0.5"
  # PE 2015.3.2 and PE 2015.3.3
  - rvm: 2.1.8
    env:
      - PUPPET_GEM_VERSION="4.3.2"
      - FACTER_GEM_VERSION="3.1.4"
      - HIERA_GEM_VERSION="3.0.6"
  # PE 2016.1.1
  - rvm: 2.1.8
    env:
      - PUPPET_GEM_VERSION="4.4.1"
      - FACTER_GEM_VERSION="3.1.5"
      - HIERA_GEM_VERSION="3.1.1"
  # PE 2016.1.2
  - rvm: 2.1.9
    env:
      - PUPPET_GEM_VERSION="4.4.2"
      - FACTER_GEM_VERSION="3.1.6"
      - HIERA_GEM_VERSION="3.1.2"
  # PE 2016.2.0 and PE 2016.2.1
  - rvm: 2.1.9
    env:
      - PUPPET_GEM_VERSION="4.5.2"
      - FACTER_GEM_VERSION="3.1.8"
      - HIERA_GEM_VERSION="3.2.0"
  # PE 2016.4.0 and PE 2016.4.2
  - rvm: 2.1.9
    env:
      - PUPPET_GEM_VERSION="4.7.0"
      - FACTER_GEM_VERSION="3.4.1"
      - HIERA_GEM_VERSION="3.2.1"
  # PE 2016.4.3
  - rvm: 2.1.9
    env:
      - PUPPET_GEM_VERSION="4.7.1"
      - FACTER_GEM_VERSION="3.4.2"
      - HIERA_GEM_VERSION="3.2.2"
  # PE 2016.5.1
  - rvm: 2.1.9
    env:
      - PUPPET_GEM_VERSION="4.8.1"
      - FACTER_GEM_VERSION="3.5.0"
      - HIERA_GEM_VERSION="3.2.2"
  # PE 2016.5.2
  - rvm: 2.1.9
    env:
      - PUPPET_GEM_VERSION="4.8.2"
      - FACTER_GEM_VERSION="3.5.1"
      - HIERA_GEM_VERSION="3.2.2"
notifications:
  email: false
